version: "3"

services:
  database_stage:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "devops_db"
    ports:
      - "3307:3307"
    volumes:
      - db-volume:/var/lib/mysql

  api_stage:
    image: devops/spring-boot
    environment:
      DB_HOST: database_stage
    ports:
      - "9090:9090"
volumes:
  db-volume:
