version: "3"

services:
  database_prod:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "devops_db"
    ports:
      - "3307:3307"
    volumes:
      - db-volume:/var/lib/mysql

  api_prod:
    image: devops/spring-boot
    environment:
      DB_HOST: database_prod
    ports:
      - "9595:9595"
volumes:
  db-volume:
