version: "3"

services:
  database_stage:
    image: mysql
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=root

  api_stage:
    image: devops/spring-boot
    environment:
      DB_HOST: database_stage
    ports:
      - "8282:8282"
volumes:
  db-volume:
