version: "3"

services:
  database_stage:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "devops_db"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql

  api_stage:
    image: devops/spring-boot
    environment:
      DB_HOST: database_stage
    ports:
      - "8282:8282"
volumes:
  db-volume:
